Fix cobra import for l3ext for ext subnet sync
External subnets cannot be properly synced, as this runs into an
exception in _find_l3_out():

AttributeError: module 'cobra.modelimpl' has no attribute 'l3ext'

This probably happened when we moved from acicobra3 to acicobra4 (or we
never had broken external subnets in a syncloop). To fix this and have
l3ext available we now import the complete path until out.